### ISSUE TITLE
Password prompt on GitHub repo using GitHub pages?

### ISSUE THREAD

**Issue by mskyttner** [jennybc/2023_raukr-purrr-pkg-dev#2]
You just mentioned something about publishing to GitHub pages with a password prompt? Sounds interesting. Can you share more info on that? 

This utility seems to take a .html and encrypt it with a password promt but runs from the command line:

```bash
# using docker image gaow/staticrypt for the utility
# takes the "staplr.html" file in the present working directory, use your own
# outputs a "staplr-encrypted.html" file that needs unlocking with the password "raukr"

docker run --rm -u $(id -u):$(id -g) -v "$(pwd):/tmp" gaow/staticrypt staticrypt /tmp/staplr.html raukr -o /tmp/staplr-encrypted.html

```

Does some R package exist that can be used to do this before publishing something via GitHub pages?

**Comment by jennybc** [comment]
The package I was thinking about is this:

https://github.com/dirkschumacher/encryptedRmd

I suspect that could be used to create encrypted html, in a private repo, with GitHub Pages turned on. In any case, an interesting experiment!

**Comment by jennybc** [comment]
Yeah, in fact the demo in the README is with GitHub Pages.

**Comment by mskyttner** [comment]
Thanks!
